# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "8fe39bfddec59c9f0f3664b5a8d02877"
name = "profitable-franchise-app"
handle = "profitable-franchise-app-7"
application_url = "https://beatles-hull-steering-horizontal.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "store-test242.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_discounts,read_orders,read_products,write_discounts,write_price_rules"

[auth]
redirect_urls = [
  "https://beatles-hull-steering-horizontal.trycloudflare.com/auth/callback",
  "https://beatles-hull-steering-horizontal.trycloudflare.com/auth/shopify/callback",
  "https://beatles-hull-steering-horizontal.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2025-04"

[pos]
embedded = false
